# Generated by Django 3.0.3 on 2020-03-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20200326_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='card_type',
            field=models.CharField(choices=[('trending_posts', 'LATEST_POSTS'), ('events', 'EVENTS'), ('coupons', 'COUPONS'), ('category', 'CATEGORY'), ('most_popular', 'MOST_POPULAR'), ('blogs', 'BLOGS'), ('blog_articles', 'BLOG_ARTICLES'), ('blog_articles_1', 'BLOG_ARTICLES_1')], default='trending_posts', max_length=100),
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Complete')),
            ],
        ),
    ]
