# Generated by Django 3.0.3 on 2020-03-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20200327_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='organized_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='blogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Complete'),
        ),
    ]
